version: 2
jobs:
  static-tests:
    working_directory: ~/nextcloud-snap
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout

      - run:
         # Run the static tests
         command: |
           apt update -qq
           apt install shellcheck -y
           ./tests/static.sh

  build:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
     - checkout

     - run:
         # Build the docker image necessary to build this snap
         command: |
           docker build -t nextcloud_builder .circleci/

     - run:
         # Build the snap
         command: |
           docker run -v $(pwd):$(pwd) \
                      -t nextcloud_builder \
                      sh -c "cd $(pwd) && apt update -qq && snapcraft"

     - run:
         # Install and run the review tools on the resulting snap
         command: |
           sudo apt update -qq
           sudo apt install -y snapd
           sudo snap install --beta review-tools
           sudo /snap/bin/review-tools.snap-review *.snap

     - run:
         # Install the snap and create an admin user
         command: |
           sudo snap install *.snap --dangerous
           sudo nextcloud.manual-install admin admin

     - run:
         # Run the integration tests
         command: ./.circleci/runtests.sh

  test-daily-master:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update -qq
            sudo apt install -y snapd
            sudo snap install --edge nextcloud
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v16:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update -qq
            sudo apt install -y snapd
            sudo snap install nextcloud --channel=16/edge
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v17:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update -qq
            sudo apt install -y snapd
            sudo snap install nextcloud --channel=17/edge
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v18:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update -qq
            sudo apt install -y snapd
            sudo snap install nextcloud --channel=18/edge
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

workflows:
  version: 2
  commit:
    jobs: [static-tests, build]

  daily-master:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-master]

  daily-v16:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v16]

  daily-v17:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v17]

  daily-v18:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v18]
