name: Manage stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v4